# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpatialModel
                                 A QGIS plugin
 This plugin creates a spatial model
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-14
        copyright            : (C) 2023 by Leonid Chashkin / HSE
        email                : lbchashkin@edu.hse.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpatialModel class from file SpatialModel.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .spatial_model import SpatialModel
    return SpatialModel(iface)
